name = "random_git"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleamyshell = ">= 2.0.1 and < 3.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
tulip = ">= 0.1.0 and < 1.0.0"

[dev-dependencies]
